services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    # restart: always
    environment:        # secrets will eventuallty be changed and moved off-file
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projectdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 

volumes: #not looking for persistence YET
  # db_data: