# # Use the official MySQL image from Docker Hub
# FROM mysql:8.0

# # Set environment variables for MySQL
# ENV MYSQL_ROOT_PASSWORD=rootpassword
# ENV MYSQL_DATABASE=projectdb
# ENV MYSQL_USER=user
# ENV MYSQL_PASSWORD=password

# # Expose the default MySQL port
# EXPOSE 3306

# # Add any custom initialization scripts if needed
# # COPY ./init.sql /docker-entrypoint-initdb.d/

# # Default command to start MySQL
# CMD ["mysqld"]