CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questions (
	id INT AUTO_INCREMENT PRIMARY KEY,
	question VARCHAR(255) NOT NULL,
	username VARCHAR(5) NOT NULL,
	votes INT DEFAULT 0
	answer VARCHAR(255) DEFAULT ''
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);