services:
  db:
    build: ./server
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 10


  frontend:
    build: ./frontend-2
    ports: 
      - "3000:80"

  adminer: #the adminer service is jsut a GUI representation of our database. note the depends-on flag, it will not start until the database has started
    image: adminer:latest
    ports:
      - "3001:8080"
    depends_on: 
      - db

  tests:
    image: mysql:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/server
    # working_dir: /server
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["bash", "./server/basic_test.sh"]

