services:
  db:
    build: ./server
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always

  frontend:
    build: ./frontend-2
    ports: 
      - "3000:80"

  adminer: #the adminer service is jsut a GUI representation of our database. note the depends-on flag, it will not start until the database has started
    image: adminer:latest
    ports:
      - "3001:8080"
    depends_on: 
      - db